### ISSUE TITLE
readme for params.rs

### ISSUE THREAD

**Issue by wyattbenno777** [SNUCP/elsa#1]
Thanks for the good work here.

A small readme for the params.rs would be appreciated as we could change these for specific performance and security traits.
What other params are possible up and down? What do they mean for speed, space complexity and security?

**Comment by sp301415** [comment]
Hi,
For the parameters, you can refer to Table 1, Page 27 of our paper: https://eprint.iacr.org/2024/306.pdf.
As with the license, we will add a python script for selecting the parameters in the next update.
Please mind that changing the parameters could break the security of our scheme.

Thanks!
